project:
  type: book
  output-dir: docs

book:
  title: "ACLR Final Project"
  author: "Rachel, Elaine, and Yuthi"
  description: "DS 2023 Final Report"
  keyword: data science, communicating, storytelling, data visualization
  url: "https://github.com/yuthimreddy/aclr-design-final#"
  sidebar: 
    logo: logo.png
    search: true
  repo-url: ""
  repo-branch: ""
  image: logo.png


  chapters:
    - index.qmd
    - cleaning.qmd
    - eda.qmd
    - viz.qmd
    - dict.qmd

# bibliography: references.bib

format:
  html:
    theme:
      light: minty
    code-fold: false
    backgroundcolor: "#FFFFFF"
  pdf:
    documentclass: scrreprt



