project:
  type: book
  output-dir: docs

book:
  title: "Factors Which Affect Reinjury Rates Among ACLR Individuals"
  author: "Rachel Seo, Elaine Liu, and Yuthi Madireddy"
  favicon: ds-l.png
  description: "DS 2023 Final Report"
  keyword: data science, communicating, storytelling, data visualization
  url: "https://yuthimreddy.github.io/aclr-design-final/"
  sidebar: 
    logo: ds-l.png
    search: true
  repo-url: "https://github.com/yuthimreddy/aclr-design-final"
  repo-branch: "master"
  image: ds-l.png


  chapters:
    - index.qmd
    - cleaning.qmd
    - eda.qmd
    - viz.qmd
    - dict.qmd


format:
  html:
    theme:
      light: 
      - minty
      - custom-fonts.scss
    code-fold: false
    backgroundcolor: "#FFFFFF"
  pdf:
    documentclass: scrreprt



